# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/adapters/proto/youtube_chat.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'src/adapters/proto/youtube_chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%src/adapters/proto/youtube_chat.proto\x12\x0eyoutube.api.v3\"@\n\x1aLiveChatMessageListRequest\x12\x14\n\x0clive_chat_id\x18\x01 \x01(\t\x12\x0c\n\x04part\x18\x64 \x03(\t\"}\n\x1bLiveChatMessageListResponse\x12\x12\n\noffline_at\x18\x02 \x01(\t\x12\x19\n\x0fnext_page_token\x18\xfa\x91\x06 \x01(\t\x12/\n\x05items\x18\xef\x07 \x03(\x0b\x32\x1f.youtube.api.v3.LiveChatMessage\"\x9c\x01\n\x0fLiveChatMessage\x12\n\n\x02id\x18\x65 \x01(\t\x12\x37\n\x07snippet\x18\x02 \x01(\x0b\x32&.youtube.api.v3.LiveChatMessageSnippet\x12\x44\n\x0e\x61uthor_details\x18\x03 \x01(\x0b\x32,.youtube.api.v3.LiveChatMessageAuthorDetails\"I\n\x1cLiveChatMessageAuthorDetails\x12\x13\n\nchannel_id\x18\xf5N \x01(\t\x12\x14\n\x0c\x64isplay_name\x18g \x01(\t\"\x9d\x01\n\x16LiveChatMessageSnippet\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x15\n\x0clive_chat_id\x18\xc9\x01 \x01(\t\x12\x14\n\x0cpublished_at\x18\x04 \x01(\t\x12H\n\x14text_message_details\x18\x13 \x01(\x0b\x32*.youtube.api.v3.LiveChatTextMessageDetails\"2\n\x1aLiveChatTextMessageDetails\x12\x14\n\x0cmessage_text\x18\x01 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.adapters.proto.youtube_chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIVECHATMESSAGELISTREQUEST']._serialized_start=57
  _globals['_LIVECHATMESSAGELISTREQUEST']._serialized_end=121
  _globals['_LIVECHATMESSAGELISTRESPONSE']._serialized_start=123
  _globals['_LIVECHATMESSAGELISTRESPONSE']._serialized_end=248
  _globals['_LIVECHATMESSAGE']._serialized_start=251
  _globals['_LIVECHATMESSAGE']._serialized_end=407
  _globals['_LIVECHATMESSAGEAUTHORDETAILS']._serialized_start=409
  _globals['_LIVECHATMESSAGEAUTHORDETAILS']._serialized_end=482
  _globals['_LIVECHATMESSAGESNIPPET']._serialized_start=485
  _globals['_LIVECHATMESSAGESNIPPET']._serialized_end=642
  _globals['_LIVECHATTEXTMESSAGEDETAILS']._serialized_start=644
  _globals['_LIVECHATTEXTMESSAGEDETAILS']._serialized_end=694
# @@protoc_insertion_point(module_scope)
